### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'complex'

### ISSUE THREAD

**Issue by CamiloMM** [absadiki/subsai#66]
After installing (no errors) and running the command `subsai-webui` I get:

```
C:\Users\<user>\miniconda3\lib\site-packages\h5py\__init__.py:36: UserWarning: h5py is running against HDF5 1.12.2 when it was built against 1.12.1, this may cause problems
  _warn(("h5py is running against HDF5 {0} when it was built against {1}, "
C:\Users\<user>\miniconda3\lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
Traceback (most recent call last):
  File "C:\Users\<user>\miniconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\<user>\miniconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\<user>\miniconda3\Scripts\subsai-webui.exe\__main__.py", line 4, in <module>
  File "C:\Users\<user>\miniconda3\lib\site-packages\subsai\__init__.py", line 1, in <module>
    from subsai.main import SubsAI, Tools
  File "C:\Users\<user>\miniconda3\lib\site-packages\subsai\main.py", line 27, in <module>
    from subsai.configs import AVAILABLE_MODELS
  File "C:\Users\<user>\miniconda3\lib\site-packages\subsai\configs.py", line 12, in <module>
    from subsai.models.whisperX_model import WhisperXModel
  File "C:\Users\<user>\miniconda3\lib\site-packages\subsai\models\whisperX_model.py", line 16, in <module>
    import whisperx
  File "C:\Users\<user>\miniconda3\lib\site-packages\whisperx\__init__.py", line 1, in <module>
    from .transcribe import load_model
  File "C:\Users\<user>\miniconda3\lib\site-packages\whisperx\transcribe.py", line 10, in <module>
    from .asr import load_model
  File "C:\Users\<user>\miniconda3\lib\site-packages\whisperx\asr.py", line 13, in <module>
    from .vad import load_vad_model, merge_chunks
  File "C:\Users\<user>\miniconda3\lib\site-packages\whisperx\vad.py", line 9, in <module>
    from pyannote.audio import Model
  File "C:\Users\<user>\miniconda3\lib\site-packages\pyannote\audio\__init__.py", line 29, in <module>
    from .core.inference import Inference
  File "C:\Users\<user>\miniconda3\lib\site-packages\pyannote\audio\core\inference.py", line 35, in <module>
    from pyannote.audio.core.model import Model
  File "C:\Users\<user>\miniconda3\lib\site-packages\pyannote\audio\core\model.py", line 45, in <module>
    from pyannote.audio.core.task import Problem, Resolution, Specifications, Task
  File "C:\Users\<user>\miniconda3\lib\site-packages\pyannote\audio\core\task.py", line 40, in <module>
    from torch_audiomentations import Identity
  File "C:\Users\<user>\miniconda3\lib\site-packages\torch_audiomentations\__init__.py", line 1, in <module>
    from .augmentations.background_noise import AddBackgroundNoise
  File "C:\Users\<user>\miniconda3\lib\site-packages\torch_audiomentations\augmentations\background_noise.py", line 11, in <module>
    from ..utils.io import Audio
  File "C:\Users\<user>\miniconda3\lib\site-packages\torch_audiomentations\utils\io.py", line 5, in <module>
    import librosa
  File "C:\Users\<user>\miniconda3\lib\site-packages\librosa\__init__.py", line 211, in <module>
    from . import core
  File "C:\Users\<user>\miniconda3\lib\site-packages\librosa\core\__init__.py", line 9, in <module>
    from .constantq import *  # pylint: disable=wildcard-import
  File "C:\Users\<user>\miniconda3\lib\site-packages\librosa\core\constantq.py", line 1059, in <module>
    dtype=np.complex,
  File "C:\Users\<user>\miniconda3\lib\site-packages\numpy\__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'complex'.
`np.complex` was a deprecated alias for the builtin `complex`. To avoid this error in existing code, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'complex_'?
```

I don't know Python/Numpy to know if this is just a case of using a deprecated type or a fault on my end, since there's no other issue about it. Is it a bug?

**Comment by abdeladim-s** [comment]
It seems like there is an issue with your Numpy or torch installation!
I would suggest to try with a fresh new virtual environment ?
